version: "3"
tasks:
  build:external:
    cmds:
      - go build -o bin/monkeyc.so -buildmode=c-shared ./api/external/main.go
    generates:
      - bin/monkeyc.h
      - bin/monkeyc.so

  build:external:all:
    cmds:
      # Darwin:
      - CGO_ENABLED=1 GOOS=darwin GOARCH=amd64 go build -o bin/darwin/monkeyc_x64.so -buildmode=c-shared ./api/external/main.go
      - CGO_ENABLED=1 GOOS=darwin GOARCH=arm64 go build -o bin/darwin/monkeyc_arm64.so -buildmode=c-shared ./api/external/main.go
      # Windows:
      - CGO_ENABLED=1 GOOS=windows GOARCH=amd64 CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ go build -o bin/windows/monkeyc_x64.so -buildmode=c-shared ./api/external/main.go
      # Linux
      - CGO_ENABLED=1 GOOS=linux GOARCH=amd64 CC=x86_64-linux-musl-gcc CXX=x86_64-linux-musl-g++ go build -o bin/linux/monkeyc_x64.so -buildmode=c-shared ./api/external/main.go
      - CGO_ENABLED=1 GOOS=linux GOARCH=arm64 CC=aarch64-linux-musl-gcc CXX=aarch64-linux-musl-g++ go build -o bin/linux/monkeyc_arm64.so -buildmode=c-shared ./api/external/main.go
