version: "3"
tasks:
  build:external:
    cmds:
      - go build -o bin/monkeyc.so -buildmode=c-shared ./api/external/main.go
    generates:
      - bin/monkeyc.h
      - bin/monkeyc.so

  build:external:all:
    cmds:
      - docker run --rm --privileged --platform linux/amd64 -v /var/run/docker.sock:/var/run/docker.sock -v ./:/monkeyc -w /monkeyc ghcr.io/gythialy/golang-cross:1.23.4 --snapshot --clean
